### ISSUE TITLE
check out lastest netty bug fixes

### ISSUE THREAD

**Issue by softprops** [softprops/unisockets#4]
since the netty modules interface touches a lot of internal interfaces http://netty.io/news/2014/12/17/3-9-6-Final-and-3-10-0-Final.html

**Comment by softprops** [comment]
when testing the netty module the tests broke when switching between netty 3.9.4.Final and 3.9.5.Final with this exception. the same was observed when making an attempt to jump right to 3.10.0. let's investigate before releasing with any version higher than 3.9.4.final

```
Jan 03, 2015 5:12:55 PM org.jboss.netty.channel.socket.nio.AbstractNioSelector
WARNING: Unexpected exception in the selector loop.
java.lang.NullPointerException
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:219)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by softprops** [comment]
for help with ^^ https://github.com/netty/netty/compare/netty-3.9.4.Final...netty-3.9.5.Final

**Comment by softprops** [comment]
was able to upgrade to 3.9.6 with a work around for [this](https://github.com/jnr/jnr-enxio/issues/6) but am holding on of 3.10.0 for now because it conflicts with my first target use for this, async http client
